import numpy as np

degrad = np.pi / 180.0

# ------ Initial Program input -----
STODE = 1  # Stochasticity in the Mean Free Path (MFP) of the electron (1=on, 0=off)
STOMFPg = 1  # Stochasticity in the MFP of the initial photon (1=on, 0=off)
jetactivated = 0  # Isotropic Blazar Emission vs Jet (1 if there is a jet, 0 otherwise)

Emin = 5  # Minimum energy of photons that reach earth
Emax = 50.0  # Maximum Energy
EBins = [
    Emin,
    20,
    35,
    Emax,
]  # Energy Bins to color code the photons. ( # E bins = len(Ebins)-1 )
Esourcecutoff = 10  # cutoff of the source photon emission in TeV

case = 4  # Case of the magnetic fields. See manual.
B0 = 1.0e-14  # magnetic field strength in gauss
dalpha = 0 * degrad  # mag field shift
hel = (
    1.0
)  # helicty of the magnetic field for case {4,5 and 6}. It takes the value 1 or -1.
beta = 45.0 * degrad  # angle of mag field in case {3} (uniform in a single direction)
cl = 250.0  # coherence length of the magnetic field in Mpc cases {4,5,6}
theta6 = 0 * degrad  # angle of mag field in case 6
phi6 = 0 * degrad  # angle of mag field in case 6
dS = 1e3  # distance of the source from earth in Mpc
k = 1  # set the kappa constant to unity
angnum = 40
maxangle = 3


# ------- Variables found below are out of date. Deleting them might cause unforeseen issues -------
# Full Sky Variables.
fullsky = False  # Set to True if doing fullsky maps, leave at False otherwise -
numflux = 200  # Number of photon of a blazar at 1 Gpc

# ---- If Using a Random Magnetic Field -----
Bfieldname = "sim_data/magfield_heleq1.npy"  # file name of the magnetic field
Lcname = (
    "sim_data/Lcutoff_heleq1.npy"
)  # file name of the cutoff/lattice spacing length in Mpc
# These files are generated by the randommagfield.savemagfield(...) function
